# Generated by Django 5.1.4 on 2025-11-09 02:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Group', '0008_santagroup_snatch_revealed_at_and_more'),
        ('Profile', '0017_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Group.santagroup')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.userprofile')),
            ],
            options={
                'ordering': ['-date_updated'],
                'unique_together': {('user_profile', 'group')},
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('store', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Wishlist.wishlist')),
            ],
            options={
                'verbose_name_plural': 'Wishlist Items',
                'ordering': ['date_created'],
            },
        ),
    ]
