# Generated by Django 4.2.7 on 2023-12-13 01:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SantaGroup',
            fields=[
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=50, unique=True)),
                ('group_code', models.CharField(default='', max_length=6, unique=True)),
                ('is_open', models.BooleanField(default=True)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('pick_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('picked_by', models.CharField(max_length=255)),
                ('date_picked', models.DateField(default=datetime.date.today)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Group.santagroup')),
            ],
            options={
                'unique_together': {('full_name', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wrapped', models.BooleanField(default=True)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField(default=datetime.date.today)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Group.santagroup')),
                ('user_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.userprofile')),
            ],
            options={
                'unique_together': {('group_id', 'user_profile_id')},
            },
        ),
    ]
