# Generated by Django 4.2.7 on 2023-12-09 21:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0021_alter_pick_group_id_alter_userprofile_group_id_and_more'),
        ('Group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField(default=datetime.date.today)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Group.santagroup')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.userprofile')),
            ],
            options={
                'unique_together': {('group_id', 'user_id')},
            },
        ),
    ]
