# Generated by Django 4.2.7 on 2023-12-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santagroup',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
