# Generated by Django 4.2.11 on 2024-12-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0002_alter_santagroup_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pick',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
