# Generated by Django 5.1.4 on 2025-10-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0003_groupmember_is_archived_pick_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='santagroup',
            name='assignment_reveal_date',
            field=models.DateTimeField(blank=True, help_text='When participants can see their assigned person', null=True),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='budget_currency',
            field=models.CharField(default='USD', help_text='Currency code (USD, EUR, etc.)', max_length=3),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum budget amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum budget amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='description',
            field=models.TextField(blank=True, help_text='Group description or rules', null=True),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='exchange_location',
            field=models.CharField(blank=True, help_text='Physical or virtual location for exchange', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='gift_exchange_deadline',
            field=models.DateTimeField(blank=True, help_text='Final date for gift exchange', null=True),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='join_deadline',
            field=models.DateTimeField(blank=True, help_text='Last date to join the group', null=True),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='theme',
            field=models.CharField(choices=[('office', 'Office'), ('family', 'Family'), ('friends', 'Friends'), ('general', 'General')], default='general', help_text='Group theme or category', max_length=20),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='wishlist_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for submitting wishlists', null=True),
        ),
    ]
