# Generated by Django 4.2.7 on 2023-12-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0023_remove_userprofile_auth_code_and_more'),
        ('Group', '0003_pick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='user_id',
            new_name='user_profile_id',
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group_id', 'user_profile_id')},
        ),
    ]
