# Generated by Django 5.1.4 on 2025-10-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0004_santagroup_assignment_reveal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santagroup',
            name='budget_currency',
            field=models.CharField(default='GBP', help_text='Currency code (GBP, USD, EUR, etc.)', max_length=3),
        ),
    ]
