# Generated by Django 4.2.7 on 2023-12-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0004_rename_user_id_groupmember_user_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='santagroup',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
