# Generated by Django 5.1.4 on 2025-10-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0005_alter_santagroup_budget_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santagroup',
            name='theme',
            field=models.CharField(choices=[('christmas', 'Christmas'), ('winter', 'Winter Holiday'), ('office', 'Office Party'), ('family', 'Family'), ('friends', 'Friends'), ('general', 'General')], default='general', help_text='Group theme or category', max_length=20),
        ),
    ]
