# Generated by Django 4.2.7 on 2023-12-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0023_remove_userprofile_auth_code_and_more'),
        ('Group', '0005_santagroup_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='santagroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.userprofile'),
        ),
    ]
