# Generated by Django 5.1.4 on 2025-10-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0006_alter_santagroup_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='santagroup',
            name='is_white_elephant',
            field=models.BooleanField(default=False, help_text='Enable White Elephant mode (gift stealing)'),
        ),
    ]
