# Generated by Django 4.2.7 on 2023-12-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0006_santagroup_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santagroup',
            name='group_code',
            field=models.CharField(default='BH1XXX', max_length=6, unique=True),
        ),
    ]
