# Generated by Django 5.1.4 on 2025-10-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0007_santagroup_is_white_elephant'),
    ]

    operations = [
        migrations.AddField(
            model_name='santagroup',
            name='snatch_revealed_at',
            field=models.DateTimeField(blank=True, help_text='When The Snatcher was revealed to them', null=True),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='snatcher_notified',
            field=models.BooleanField(default=False, help_text='Has The Snatcher been notified?'),
        ),
        migrations.AddField(
            model_name='santagroup',
            name='snatcher_user_id',
            field=models.IntegerField(blank=True, help_text='The user chosen as The Snatcher', null=True),
        ),
    ]
