# Generated by Django 4.2.7 on 2023-12-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0007_alter_santagroup_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='santagroup',
            name='group_code',
            field=models.CharField(default='5VOBKP', max_length=6, unique=True),
        ),
    ]
