# Generated by Django 5.1.4 on 2025-11-21 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0008_santagroup_snatch_revealed_at_and_more'),
        ('Profile', '0018_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pick',
            name='picked_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('group_id', 'picked_profile'), name='unique_pick_per_group'),
        ),
    ]
