# Generated by Django 5.1.4 on 2025-11-21 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0009_alter_pick_unique_together_pick_picked_profile_and_more'),
        ('Profile', '0018_alter_userprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='picked_by',
        ),
        migrations.AddField(
            model_name='pick',
            name='picked_by_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks_made', to='Profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='picked_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picks_received', to='Profile.userprofile'),
        ),
    ]
