# Generated by Django 4.2.7 on 2023-12-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0009_alter_santagroup_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_wrapped',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='santagroup',
            name='group_code',
            field=models.CharField(default='NQORXF', max_length=6, unique=True),
        ),
    ]
