# Generated by Django 5.1.4 on 2025-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0010_remove_pick_full_name_remove_pick_picked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
