# Generated by Django 4.2.7 on 2023-12-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0010_groupmember_is_wrapped_alter_santagroup_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='picked_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='santagroup',
            name='group_code',
            field=models.CharField(default='N7F9YR', max_length=6, unique=True),
        ),
    ]
