# Generated by Django 5.1.4 on 2025-11-22 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0011_pick_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santagroup',
            name='assignment_reveal_date',
        ),
        migrations.RemoveField(
            model_name='santagroup',
            name='wishlist_deadline',
        ),
    ]
