# Generated by Django 4.2.7 on 2023-12-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_userprofile_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='password_changed',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
