# Generated by Django 4.2.7 on 2023-12-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_santagroup_group_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='santagroup',
            name='group_users',
        ),
        migrations.AlterField(
            model_name='santagroup',
            name='group_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
