# Generated by Django 4.2.1 on 2023-12-04 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_remove_santagroup_group_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_updated',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
