# Generated by Django 4.2.1 on 2023-12-04 14:46

import Auth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_userprofile_auth_code_userprofile_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth_code',
            field=models.CharField(default=Auth.utils.authCodeGenerator, max_length=6),
        ),
    ]
