# Generated by Django 4.2.1 on 2023-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_alter_userprofile_auth_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth_code',
            field=models.CharField(default='F2AXME', max_length=6),
        ),
    ]
