# Generated by Django 4.2.1 on 2023-12-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_alter_userprofile_auth_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'Female'), ('Non-binary', 'Non-binary')], max_length=11),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
