# Generated by Django 4.2.7 on 2023-12-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_wrapped',
            field=models.BooleanField(default=True),
        ),
    ]
