# Generated by Django 4.2.11 on 2024-12-06 00:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField(default=datetime.date.today)),
                ('is_archived', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Wish Lists',
                'ordering': ['date_created'],
            },
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
