# Generated by Django 4.2.11 on 2024-12-06 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_wishlistitem_delete_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['date_created'], 'verbose_name_plural': 'Wish Lists Items'},
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='is_archived',
        ),
    ]
