# Generated by Django 4.2.7 on 2023-12-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='picked_by',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pick',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together={('full_name', 'group_id')},
        ),
    ]
