# Generated by Django 4.2.11 on 2024-12-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_alter_wishlistitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
