# Generated by Django 5.1.4 on 2024-12-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_alter_wishlistitem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
