# Generated by Django 4.2.7 on 2023-12-06 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_pick_picked_by_alter_pick_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pick',
            name='group_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Profile.santagroup'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='picked_by',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
