# Generated by Django 5.1.4 on 2024-12-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_alter_wishlistitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
