# Generated by Django 4.2.7 on 2023-12-06 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0014_alter_pick_full_name_alter_pick_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.santagroup'),
        ),
    ]
