# Generated by Django 4.2.7 on 2023-12-08 13:25

import Auth.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0015_alter_pick_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='santagroup',
            name='group_code',
            field=models.CharField(default=Auth.utils.groupJoinCode, max_length=6),
        ),
    ]
