# Generated by Django 5.1.4 on 2025-08-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0016_userprofile_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SUPPORT', 'Support'), ('MAINTAINER', 'Maintainer')], default='USER', max_length=50),
        ),
    ]
