# Generated by Django 4.2.7 on 2023-12-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_rename_group_id_pick_group_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='group_name',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='group_name',
            new_name='group_id',
        ),
        migrations.AlterUniqueTogether(
            name='pick',
            unique_together={('full_name', 'group_id')},
        ),
    ]
