# Generated by Django 4.2.7 on 2023-12-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0021_alter_pick_group_id_alter_userprofile_group_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pick',
        ),
    ]
