# Generated by Django 4.2.7 on 2023-12-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0022_delete_pick'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='auth_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_authenticated',
        ),
    ]
