# Generated by Django 4.2.7 on 2023-12-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0023_remove_userprofile_auth_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_wrapped',
        ),
    ]
